### ISSUE TITLE
Add delay to triggers

### ISSUE THREAD

**Issue by sziyan** [zenangst/KeyboardCowboy#385] opened 2023-09-26 07:50 UTC
Thanks for the wonderful app. 

Im using this to potentially replace Karabiner Elements.

Would you be able to add in a option to enable delay triggers?

Use case:
I am using tab + somekey as a app launcher (e.g Tab + C will launch VSCode, Tab + T will launch Telegram)
However, as tab is the trigger key, there are times when I want to use tab as itself and unable to do so.

Adding a delay option will tell KeyboardCowboy that only holding trigger key for (e.g 2 seconds) will be used in workflow.

End Result:
Pressing tab once and releasing immediately -> Not used as trigger key. Tab will function as per normal
Holding tab for 2 sec (if delay is configured for 2sec) -> Tab is used as trigger key. Any follow up keys will trigger the workflows configured.

Thanks in advance!

**Comment by zenangst** [comment] 2023-09-26 09:58
@sziyan hey mate, did you mean the "hold for X seconds" feature?
Just wanted to double check because you closed the issue 😎

**Comment by sziyan** [comment] 2023-09-26 11:05
@zenangst yes thats what I am referring to but noticed it was already implemented (from past closed issue)
But after closing I noticed  I am unable to find that option anywhere. Will you be able to point me in the right direction?

Basically a option where it requires me holding the trigger key for X seconds of time before it will be used as a trigger key.

**Comment by zenangst** [comment] 2023-09-26 11:11
@sziyan Oh, I think we just find a small bug here.
If you add a keyboard shortcut to a workflow, it doesn't show the option directly. 

It's suppose to appear here:
![image](https://github.com/zenangst/KeyboardCowboy/assets/57446/bfff4197-858d-4253-8e02-3be1f3b3375b)


You need to select the workflow again for it to appear. I'll re-open this issue and close it when I fix the bug.

**Comment by zenangst** [comment] 2023-09-26 11:39
@sziyan found the bug and fixed it here - https://github.com/zenangst/KeyboardCowboy/pull/386

It will make its way into the next version, which should be available soon-ish.

**Closed** 2023-09-26 11:52 UTC

**Comment by zenangst** [comment] 2023-09-26 16:02
@sziyan a new version is out - https://github.com/zenangst/KeyboardCowboy/releases/tag/3.13.2

**Comment by hasantahir** [comment] 2024-02-20 11:55
Hi,

Trying out this after finding it from Reddit. Great work! 

Is it possible to have decimal values placed in the Hold for second entry? Like 0.2?

Thanks

**Comment by zenangst** [comment] 2024-02-20 13:05
Hey @hasantahir, thanks for the kind words ❤️ 

You should be able to use decimal values here.
However, while verifying this I found a bug. It seems like we convert into an Int in the UI. So you might see that the value does not represent the given values. This is a UI bug so it should still work as intended.

I'll fix this in the next version, working on some improvements to Macros right now... but the new patch version shouldn't be too far out.

**Comment by hasantahir** [comment] 2024-02-20 13:47
You are most welcome. I currently use hammerspoon and Karabiner elements for many things that Keyboard Cowboy does. Eager to learn more about the app. Think this is the most exciting app coming out on the macapps subreddit for a while.

**Comment by zenangst** [comment] 2024-02-20 14:09
@hasantahir ❤️ 

If you have any questions, just let me know. You might also want to take a peek at the wiki (https://github.com/zenangst/KeyboardCowboy/wiki). I try to go into a bit more detail there on how things work.

**Comment by zenangst** [comment] 2024-02-20 14:42
@hasantahir 3.22.2 is ready for download https://github.com/zenangst/KeyboardCowboy/releases/tag/3.22.2 :)

**Comment by hasantahir** [comment] 2024-02-20 16:05
To the hat in the icon

![giphy](https://github.com/zenangst/KeyboardCowboy/assets/11236148/4a4ae5d8-ea5a-4746-8f36-4d146412e616)

Thanks
